apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: reg.gabtec.pt/kube/goapp
  newTag: c2e8fb99e16775a980495c0298a5134ae5cf1fc4
