apiVersion: v1
kind: Service
metadata:
  name: goapp
spec:
  selector:
    app: goapp
  # type: LoadBalancer | ClusterIP | NodePort
  ports:
    - name: service-port
      port: 8080 # service port
      targetPort: 8080 # container port
