name: CD
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image and push to registry
        uses: docker/build-push-action@v1.1.0
        with:
          username: gabtec
          password: ${{ secrets.REG_PASSWORD }}
          repository: reg.gabtec.pt/kube/goapp
          tags: ${{ github.sha }}, latest
