name: CD
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: reg.gabtec.pt/kube/goapp:latest, reg.gabtec.pt/kube/goapp:${{ github.sha }}
      # - name: Checkout
      #   uses: actions/checkout@v2

      # - name: Build image and push to registry
      #   uses: docker/build-push-action@v1.1.0
      #   with:
      #     username: gabtec
      #     password: ${{ secrets.REG_PASSWORD }}
      #     repository: reg.gabtec.pt/kube/goapp
      #     tags: ${{ github.sha }}, latest
